apiVersion: v1
kind: ConfigMap
metadata:
  name: promconfig
data:
  prometheus.yml: |
    
    global:
      scrape_interval:     15s 
      evaluation_interval: 15s  
    
    alerting:
      alertmanagers:
      - static_configs:
        - targets:

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'Node1'
      static_configs:
        - targets: ['192.168.43.121:9100']
